server {
    ## port 8000 ийн хүсэлтүүдийг унших 
    listen 8000;

    ## default server_name нь _ байна.
    server_name _;

    ## public хавтасны файлуудыг унших
    ## энэ нь public/ index.php ийг ажлуулж уншиж байх шиг байсан. 
    root /app/public;
    index index.php;
    
    charset utf-8;

    ## хүсэлтийн мэдээллийг хадгалах газар заах
    access_log /dev/stdout;
    ## алдааны мэдээллийг хадгалах газар заах
    error_log /dev/stderr;

    ## 12MB хүртэлх хэмжээтэй файлуудыг хүлээн авах
    client_max_body_size 12m;

    ## default хүсэлтүүдийг хүлээн авах
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    ## .php өргөтгөлтэй файлуудыг дамжуулах. Гэхдээ энэ хэсгийг сайн ойлгоогүй
    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT   $realpath_root;
    }

}