; =============================================================================

[supervisord]
nodaemon=true
user=root

; ------------------------------------------------------------------ web ---
[program:web]

directory=/app/public
command=php -S 0.0.0.0:8000 /app/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

; ---------------------------------------------------------------- queue ---
[program:queue]
directory=/app
command=php artisan queue:work --tries=3 --backoff=5
autostart=true
autorestart=true
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
